- name: Collect metrics from vSphere
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Collect VM metrics
      vmware_vm_info:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
      register: vm_info

    - name: Collect Host metrics
      vmware_host_facts:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
      register: host_info

    - name: Save VM metrics to file
      copy:
        content: "{{ vm_info.virtual_machines | to_json }}"
        dest: /tmp/vm_metrics.json

    - name: Save Host metrics to file
      copy:
        content: "{{ host_info.esxi_hosts | to_json }}"
        dest: /tmp/host_metrics.json
